#include <QtTest/QTest>

#include <QtCore/QFile>
#include <QtCore/QTemporaryDir>
#include <chrono>
#include <filesystem>
#include <string>
#include "../src/infrastructure/pmdg/PmdgRouteFile.h"

namespace
{
    long long NowEpoch()
    {
        return std::chrono::duration_cast<std::chrono::seconds>(
            std::chrono::system_clock::now().time_since_epoch()).count();
    }

    void WriteFile(const QTemporaryDir& dir, const QString& name)
    {
        QFile file(dir.filePath(name));
        file.open(QIODevice::WriteOnly);
        file.write("Generated by SimBrief\n");
        file.close();
    }

    std::filesystem::path PathOf(const QTemporaryDir& dir)
    {
        return std::filesystem::path(dir.path().toStdWString());
    }
}

class PmdgRouteFileTest final : public QObject
{
    Q_OBJECT

private slots:
    static void directorySitsBesideTheOptionsFile();
    static void unknownAircraftHasNoDirectory();
    static void acceptsThePlainAndTheNumberedNames();
    static void rejectsAnotherPairAndAnotherExtension();
    static void findsTheRouteWrittenAfterThePlan();
    static void ignoresARouteOlderThanThePlan();
    static void missingDirectoryIsNotAnImport();
};

void PmdgRouteFileTest::directorySitsBesideTheOptionsFile()
{
    const auto directory = PmdgRouteFile::DirectoryFor("PMDG 737-800BCF");

    QVERIFY(directory.has_value());
    QCOMPARE(directory->filename().string(), std::string("Flightplans"));
    QCOMPARE(directory->parent_path().filename().string(), std::string("work"));
    QCOMPARE(directory->parent_path().parent_path().filename().string(), std::string("pmdg-aircraft-738"));
}

void PmdgRouteFileTest::unknownAircraftHasNoDirectory()
{
    QCOMPARE(PmdgRouteFile::DirectoryFor("ToLiss A340-600"), std::nullopt);
}

void PmdgRouteFileTest::acceptsThePlainAndTheNumberedNames()
{
    QVERIFY(PmdgRouteFile::NamesPlan("SBFZSBTE.rte", "SBFZ", "SBTE"));
    QVERIFY(PmdgRouteFile::NamesPlan("SBFZSBTE.1.rte", "SBFZ", "SBTE"));
    QVERIFY(PmdgRouteFile::NamesPlan("SBFZSBTE001.rte", "SBFZ", "SBTE"));
    QVERIFY(PmdgRouteFile::NamesPlan("sbfzsbte.rte", "SBFZ", "SBTE"));
}

void PmdgRouteFileTest::rejectsAnotherPairAndAnotherExtension()
{
    QVERIFY(!PmdgRouteFile::NamesPlan("SBGRSBTE.rte", "SBFZ", "SBTE"));
    QVERIFY(!PmdgRouteFile::NamesPlan("SBFZSBTE.wx", "SBFZ", "SBTE"));
    QVERIFY(!PmdgRouteFile::NamesPlan("SBFZSBTE.rte", "", "SBTE"));
}

void PmdgRouteFileTest::findsTheRouteWrittenAfterThePlan()
{
    const QTemporaryDir dir;
    WriteFile(dir, "SBFZSBTE.rte");

    QVERIFY(PmdgRouteFile::ImportedSince(PathOf(dir), "SBFZ", "SBTE", NowEpoch() - 60));
    QVERIFY(!PmdgRouteFile::ImportedSince(PathOf(dir), "SBGR", "SBSP", NowEpoch() - 60));
}

void PmdgRouteFileTest::ignoresARouteOlderThanThePlan()
{
    const QTemporaryDir dir;
    WriteFile(dir, "SBFZSBTE.rte");

    QVERIFY(!PmdgRouteFile::ImportedSince(PathOf(dir), "SBFZ", "SBTE", NowEpoch() + 3600));
}

void PmdgRouteFileTest::missingDirectoryIsNotAnImport()
{
    const QTemporaryDir dir;

    QVERIFY(!PmdgRouteFile::ImportedSince(PathOf(dir) / "Flightplans", "SBFZ", "SBTE", 0));
}

QTEST_APPLESS_MAIN(PmdgRouteFileTest)

#include "tst_pmdg_route_file.moc"
