#include <QtTest/QTest>

#include <QtCore/QFile>
#include <QtCore/QTemporaryDir>
#include <chrono>
#include <filesystem>
#include <string>
#include "../src/infrastructure/pmdg/PmdgRouteFile.h"

namespace
{
    long long NowEpoch()
    {
        return std::chrono::duration_cast<std::chrono::seconds>(
            std::chrono::system_clock::now().time_since_epoch()).count();
    }

    void WriteFile(const QTemporaryDir& dir, const QString& name)
    {
        QFile file(dir.filePath(name));
        file.open(QIODevice::WriteOnly);
        file.write("Generated by SimBrief\n");
        file.close();
    }

    void Restamp(const QTemporaryDir& dir, const QString& name, const long long epochSeconds)
    {
        const std::filesystem::path file(dir.filePath(name).toStdWString());
        const auto stamp = std::chrono::system_clock::time_point(std::chrono::seconds(epochSeconds));
        std::filesystem::last_write_time(file, std::chrono::clock_cast<std::chrono::file_clock>(stamp));
    }

    std::filesystem::path PathOf(const QTemporaryDir& dir)
    {
        return std::filesystem::path(dir.path().toStdWString());
    }
}

class PmdgRouteFileTest final : public QObject
{
    Q_OBJECT

private slots:
    static void directorySitsBesideTheOptionsFile();
    static void unknownAircraftHasNoDirectory();
    static void acceptsThePlainAndTheNumberedNames();
    static void rejectsAnotherPairAndAnotherExtension();
    static void reportsTheNewestMatchingWrite();
    static void missingDirectoryHasNoWrite();
    static void ignoresARouteThatWasAlreadyThere();
    static void seesARouteWrittenAfterTheBaseline();
    static void rearmsWhenThePlanChanges();
};

void PmdgRouteFileTest::directorySitsBesideTheOptionsFile()
{
    const auto directory = PmdgRouteFile::DirectoryFor("PMDG 737-800BCF");

    QVERIFY(directory.has_value());
    QCOMPARE(directory->filename().string(), std::string("Flightplans"));
    QCOMPARE(directory->parent_path().filename().string(), std::string("work"));
    QCOMPARE(directory->parent_path().parent_path().filename().string(), std::string("pmdg-aircraft-738"));
}

void PmdgRouteFileTest::unknownAircraftHasNoDirectory()
{
    QCOMPARE(PmdgRouteFile::DirectoryFor("ToLiss A340-600"), std::nullopt);
}

void PmdgRouteFileTest::acceptsThePlainAndTheNumberedNames()
{
    QVERIFY(PmdgRouteFile::NamesPlan("SBFZSBTE.rte", "SBFZ", "SBTE"));
    QVERIFY(PmdgRouteFile::NamesPlan("SBFZSBTE.1.rte", "SBFZ", "SBTE"));
    QVERIFY(PmdgRouteFile::NamesPlan("SBFZSBTE001.rte", "SBFZ", "SBTE"));
    QVERIFY(PmdgRouteFile::NamesPlan("sbfzsbte.rte", "SBFZ", "SBTE"));
}

void PmdgRouteFileTest::rejectsAnotherPairAndAnotherExtension()
{
    QVERIFY(!PmdgRouteFile::NamesPlan("SBGRSBTE.rte", "SBFZ", "SBTE"));
    QVERIFY(!PmdgRouteFile::NamesPlan("SBFZSBTE.wx", "SBFZ", "SBTE"));
    QVERIFY(!PmdgRouteFile::NamesPlan("SBFZSBTE.rte", "", "SBTE"));
}

void PmdgRouteFileTest::reportsTheNewestMatchingWrite()
{
    const QTemporaryDir dir;
    WriteFile(dir, "SBFZSBTE.rte");
    Restamp(dir, "SBFZSBTE.rte", NowEpoch() - 600);
    WriteFile(dir, "SBFZSBTE01.rte");
    Restamp(dir, "SBFZSBTE01.rte", NowEpoch() - 60);

    QCOMPARE(PmdgRouteFile::LatestWrite(PathOf(dir), "SBFZ", "SBTE"), NowEpoch() - 60);
    QCOMPARE(PmdgRouteFile::LatestWrite(PathOf(dir), "SBGR", "SBSP"), 0LL);
}

void PmdgRouteFileTest::missingDirectoryHasNoWrite()
{
    const QTemporaryDir dir;

    QCOMPARE(PmdgRouteFile::LatestWrite(PathOf(dir) / "Flightplans", "SBFZ", "SBTE"), 0LL);
}

void PmdgRouteFileTest::ignoresARouteThatWasAlreadyThere()
{
    const QTemporaryDir dir;
    WriteFile(dir, "SBFZSBTE.rte");
    Restamp(dir, "SBFZSBTE.rte", NowEpoch() - 60);

    PmdgRouteImport watch;
    watch.Observe(PathOf(dir), "SBFZ", "SBTE", 1000);

    QVERIFY(!watch.Seen());

    watch.Observe(PathOf(dir), "SBFZ", "SBTE", 1000);

    QVERIFY(!watch.Seen());
}

void PmdgRouteFileTest::seesARouteWrittenAfterTheBaseline()
{
    const QTemporaryDir dir;
    WriteFile(dir, "SBFZSBTE.rte");
    Restamp(dir, "SBFZSBTE.rte", NowEpoch() - 60);

    PmdgRouteImport watch;
    watch.Observe(PathOf(dir), "SBFZ", "SBTE", 1000);

    Restamp(dir, "SBFZSBTE.rte", NowEpoch());
    watch.Observe(PathOf(dir), "SBFZ", "SBTE", 1000);

    QVERIFY(watch.Seen());
}

void PmdgRouteFileTest::rearmsWhenThePlanChanges()
{
    const QTemporaryDir dir;
    WriteFile(dir, "SBFZSBTE.rte");
    Restamp(dir, "SBFZSBTE.rte", NowEpoch() - 60);

    PmdgRouteImport watch;
    watch.Observe(PathOf(dir), "SBFZ", "SBTE", 1000);
    Restamp(dir, "SBFZSBTE.rte", NowEpoch());
    watch.Observe(PathOf(dir), "SBFZ", "SBTE", 1000);

    QVERIFY(watch.Seen());

    watch.Observe(PathOf(dir), "SBFZ", "SBTE", 2000);

    QVERIFY(!watch.Seen());

    watch.Observe(PathOf(dir), "SBFZ", "SBTE", 2000);

    QVERIFY(!watch.Seen());
}

QTEST_APPLESS_MAIN(PmdgRouteFileTest)

#include "tst_pmdg_route_file.moc"
