#ifndef GSX_INTEGRATOR_CLIENT_DOMAIN_RULECADENCE_H
#define GSX_INTEGRATOR_CLIENT_DOMAIN_RULECADENCE_H

enum class RuleCadence
{
    Fast,
    Slow
};

#endif // GSX_INTEGRATOR_CLIENT_DOMAIN_RULECADENCE_H
