#ifndef GSX_INTEGRATOR_CLIENT_DOMAIN_DOORSTATUS_H
#define GSX_INTEGRATOR_CLIENT_DOMAIN_DOORSTATUS_H

enum class DoorStatus { Unknown, AnyOpen, AllClosed };

#endif // GSX_INTEGRATOR_CLIENT_DOMAIN_DOORSTATUS_H
