#ifndef GSX_INTEGRATOR_CLIENT_DOMAIN_GROUNDPOWERSTATUS_H
#define GSX_INTEGRATOR_CLIENT_DOMAIN_GROUNDPOWERSTATUS_H

enum class GroundPowerStatus { Unknown, Connected, Disconnected };

#endif // GSX_INTEGRATOR_CLIENT_DOMAIN_GROUNDPOWERSTATUS_H
