set(TURNAROUND_STATE_SOURCES
        src/domain/turnaround/TurnaroundData.h
        src/domain/turnaround/TurnaroundTransition.h
        src/domain/turnaround/TurnaroundContext.h
        src/domain/turnaround/TurnaroundMath.h
        src/domain/turnaround/states/TurnaroundState.h
        src/domain/turnaround/states/WaitingFlightPlanState.cpp
        src/domain/turnaround/states/WaitingFlightPlanState.h
        src/domain/turnaround/states/RequestFuelState.cpp
        src/domain/turnaround/states/RequestFuelState.h
        src/domain/turnaround/states/RefuelingState.cpp
        src/domain/turnaround/states/RefuelingState.h
        src/domain/turnaround/states/RequestBoardingState.cpp
        src/domain/turnaround/states/RequestBoardingState.h
        src/domain/turnaround/states/BoardingState.cpp
        src/domain/turnaround/states/BoardingState.h
        src/domain/turnaround/states/RequestPushbackState.cpp
        src/domain/turnaround/states/RequestPushbackState.h
        src/domain/turnaround/states/WaitingPushbackToStartState.cpp
        src/domain/turnaround/states/WaitingPushbackToStartState.h
        src/domain/turnaround/states/WaitingEnginesState.cpp
        src/domain/turnaround/states/WaitingEnginesState.h
        src/domain/turnaround/states/WaitingSupportedAircraftState.cpp
        src/domain/turnaround/states/WaitingSupportedAircraftState.h
        src/domain/turnaround/states/WaitingPowerOnState.cpp
        src/domain/turnaround/states/WaitingPowerOnState.h
        src/domain/turnaround/states/WaitingAircraftReadyState.cpp
        src/domain/turnaround/states/WaitingAircraftReadyState.h
        src/domain/turnaround/states/WaitingReadyToPushState.cpp
        src/domain/turnaround/states/WaitingReadyToPushState.h
        src/domain/turnaround/states/CallStairsOrJetwayState.cpp
        src/domain/turnaround/states/CallStairsOrJetwayState.h
        src/domain/turnaround/states/RepositionAircraftState.cpp
        src/domain/turnaround/states/RepositionAircraftState.h
        src/domain/turnaround/states/WaitingDepartureState.cpp
        src/domain/turnaround/states/WaitingDepartureState.h
        src/domain/turnaround/states/OnFlightState.h
        src/domain/turnaround/states/OnFlightState.cpp
        src/domain/turnaround/states/WaitingEngineShutdownState.cpp
        src/domain/turnaround/states/WaitingEngineShutdownState.h
        src/domain/turnaround/states/RequestDeboardingState.cpp
        src/domain/turnaround/states/RequestDeboardingState.h
        src/domain/turnaround/states/DeboardingState.cpp
        src/domain/turnaround/states/DeboardingState.h
        src/domain/turnaround/states/WaitingNewFlightState.cpp
        src/domain/turnaround/states/WaitingNewFlightState.h
)

set(TURNAROUND_SOURCES
        ${TURNAROUND_STATE_SOURCES}
        src/domain/turnaround/TurnaroundStateMachine.cpp
        src/domain/turnaround/TurnaroundStateMachine.h
)

set(APP_SOURCES
        assets/app.rc
        assets/resources.qrc
        src/main.cpp
        src/application/model/CommandResult.h
        src/application/ports/IntegratorService.h
        src/application/ports/SettingsRepository.h
        src/application/IntegratorRuntime.cpp
        src/application/IntegratorRuntime.h
        src/application/RuntimeIntegratorService.cpp
        src/application/RuntimeIntegratorService.h
        src/application/model/AppSettings.h
        src/application/model/IntegratorSnapshot.h
        src/domain/model/AutomationStatus.h
        src/domain/model/AutomationSettings.h
        src/domain/model/FlightPlan.h
        src/domain/model/FlightPlan.h
        src/domain/turnaround/TurnaroundPhase.h
        src/domain/ports/Aircraft.h
        src/domain/ports/GsxGateway.h
        ${TURNAROUND_SOURCES}
        src/domain/support/Weight.h
        src/infrastructure/aircraft/AircraftFactory.cpp
        src/infrastructure/aircraft/AircraftFactory.h
        src/infrastructure/aircraft/AircraftIdentity.h
        src/infrastructure/aircraft/AircraftRegistry.cpp
        src/infrastructure/aircraft/AircraftRegistry.h
        src/infrastructure/aircraft/TfdiMd11.cpp
        src/infrastructure/aircraft/TfdiMd11.h
        src/infrastructure/commbus/CommBusPluginClient.cpp
        src/infrastructure/commbus/CommBusPluginClient.h
        src/infrastructure/gsx/GsxStateService.cpp
        src/infrastructure/gsx/GsxStateService.h
        src/infrastructure/logging/LogMacros.h
        src/infrastructure/simbrief/SimbriefClient.cpp
        src/infrastructure/simbrief/SimbriefClient.h
        src/infrastructure/simbrief/SimbriefOfpParser.cpp
        src/infrastructure/simbrief/SimbriefOfpParser.h
        src/infrastructure/settings/QSettingsRepository.cpp
        src/infrastructure/settings/QSettingsRepository.h
        src/infrastructure/simvars/VariableGateway.h
        src/infrastructure/simconnect/SimConnectSession.cpp
        src/infrastructure/simconnect/SimConnectSession.h
        src/infrastructure/simconnect/SimConnectVariableGateway.cpp
        src/infrastructure/simconnect/SimConnectVariableGateway.h
        src/viewmodel/OperationsViewModel.cpp
        src/viewmodel/OperationsViewModel.h
        src/viewmodel/SettingsViewModel.cpp
        src/viewmodel/SettingsViewModel.h
        src/domain/ports/GsxMenuGateway.h
        src/infrastructure/gsx/GsxMenuNavigator.cpp
        src/infrastructure/gsx/GsxMenuNavigator.h
        src/domain/ports/DomainLogger.h
        src/infrastructure/logging/QtDomainLogger.cpp
        src/infrastructure/logging/QtDomainLogger.h
        src/application/sim/SessionReadiness.h
        src/application/sim/SimVersion.h
        src/infrastructure/gsx/GsxRemoteState.h
        src/infrastructure/gsx/GsxRemoteStateReducer.cpp
        src/infrastructure/gsx/GsxRemoteStateReducer.h
        src/infrastructure/gsx/GsxRemoteApiClient.h
        src/infrastructure/gsx/GsxRemoteApiClient.cpp
)

set(APP_QML_FILES
        src/qml/Main.qml
        src/qml/Theme.qml
        src/qml/components/ActionButton.qml
        src/qml/components/Advisory.qml
        src/qml/components/DataCard.qml
        src/qml/components/HeaderButton.qml
        src/qml/components/HelpHint.qml
        src/qml/components/KeyValueRow.qml
        src/qml/components/SegmentedControl.qml
        src/qml/components/SettingRow.qml
        src/qml/components/SquareSwitch.qml
        src/qml/components/StatusChip.qml
        src/qml/components/SwitchRow.qml
        src/qml/screens/AboutScreen.qml
        src/qml/screens/ConnectingPanel.qml
        src/qml/screens/OperationsScreen.qml
        src/qml/screens/SettingsScreen.qml
)
